<?php

namespace App\Helpers;

class LanguageHelper
{
    public static function getLanguageName($code)
    {
        $languages = [
            'en' => 'English',
            'zh-Hant' => 'Chinese (Traditional)',
            'zh-Hans' => 'Chinese (Simplified)',
            'es' => 'Spanish',
            'fr' => 'French',
            'de' => 'German',
            'ja' => 'Japanese',
            'ko' => 'Korean',
            'ar' => 'Arabic',
            'ru' => 'Russian',
            'pt' => 'Portuguese',
            'it' => 'Italian',
            'hi' => 'Hindi',
            'bn' => 'Bengali',
            'pa' => 'Punjabi',
            'jv' => 'Javanese',
            'ms' => 'Malay',
            'sw' => 'Swahili',
            'vi' => 'Vietnamese',
            'th' => 'Thai',
            'tr' => 'Turkish',
            'nl' => 'Dutch',
            'el' => 'Greek',
            'he' => 'Hebrew',
            'sv' => 'Swedish',
            'fi' => 'Finnish',
            'no' => 'Norwegian',
            'da' => 'Danish',
            'hu' => 'Hungarian',
            'pl' => 'Polish',
            'cs' => 'Czech',
            'sk' => 'Slovak',
            'uk' => 'Ukrainian',
            'ro' => 'Romanian',
            'bg' => 'Bulgarian',
            'sr' => 'Serbian',
            'hr' => 'Croatian',
            'lt' => 'Lithuanian',
            'lv' => 'Latvian',
            'et' => 'Estonian',
            'sl' => 'Slovenian',
            'is' => 'Icelandic',
            'mt' => 'Maltese',
            'ga' => 'Irish',
            'cy' => 'Welsh',
            'ta' => 'Tamil',
            'te' => 'Telugu',
            'ml' => 'Malayalam',
            'kn' => 'Kannada',
            'mr' => 'Marathi',
            'gu' => 'Gujarati',
            'ur' => 'Urdu',
            'fa' => 'Persian',
            'am' => 'Amharic',
            'ne' => 'Nepali',
            'si' => 'Sinhala',
            'my' => 'Burmese',
            'km' => 'Khmer',
            'lo' => 'Lao',
            'mn' => 'Mongolian',
            'tg' => 'Tajik',
            'kk' => 'Kazakh',
            'uz' => 'Uzbek',
            'az' => 'Azerbaijani',
            'hy' => 'Armenian',
            'ka' => 'Georgian',
            'af' => 'Afrikaans',
            'zu' => 'Zulu',
            'xh' => 'Xhosa',
            'st' => 'Sesotho',
            'ts' => 'Tsonga',
            'tn' => 'Tswana',
            've' => 'Venda',
            'nr' => 'Ndebele',
            'ss' => 'Swati',
            'ny' => 'Chichewa',
            'yo' => 'Yoruba',
            'ig' => 'Igbo',
            'ha' => 'Hausa',
            'rw' => 'Kinyarwanda',
            'om' => 'Oromo',
            'so' => 'Somali',
            'sn' => 'Shona',
            'ti' => 'Tigrinya',
            'ak' => 'Akan',
            'ee' => 'Ewe',
            'tw' => 'Twi',
            'bm' => 'Bambara',
            'wo' => 'Wolof',
            'kmr' => 'Kurdish (Kurmanji)',
            'ckb' => 'Kurdish (Sorani)',
            'ku' => 'Kurdish',
        ];

        return $languages[$code] ?? 'Unknown';
    }
}
